### PR TITLE
Packaging updates

### PR DESCRIPTION
**Pull request by cgzones**
* Add build depends package to symbols file
Found by Lintian:

      I: libjbig0: symbols-file-missing-build-depends-package-field libjbig.so.0 [symbols]
      N:
      N:   The symbols file for this package does not contain a Build-Depends-Package meta-information field.
      N:
      N:   This field specifies the name of the -dev package associated to the library and is used by dpkg-shlibdeps(1) to make sure that the dependency generated is at least as strict as the corresponding build dependency.
      N:
      N:   This is useful as allows packages to not hardcode this information multiple times.
      N:
      N:   Note that the format of deb-symbols(5) files requires that the * Build-Depends-Package: line should start in column one of the file and not be indented to align with the symbols themselves. Please do not use the placeholder #PACKAGE#. The development package for
      N:   your shared library must be stated explicitly.
      N:
      N:   Please refer to The symbols File Format (Section 8.6.3.2) in the Debian Policy Manual, the deb-symbols(5) manual page, the dpkg-shlibdeps(1) manual page, https://www.debian.org/doc/manuals/maint-guide/advanced.en.html#librarysymbols, and Bug#944047 for details.
      N:
      N:   Visibility: info
      N:   Show-Always: no
      N:   Check: debian/shlibs

* Enable hardening flags
Found by Lintian:

      I: jbigkit-bin: hardening-no-bindnow [usr/bin/jbgtopbm85]
      N:
      N:   This package provides an ELF binary that lacks the "bindnow" linker flag.
      N:
      N:   This is needed (together with "relro") to make the "Global Offset Table" (GOT) fully read-only. The bindnow feature trades startup time for improved security. Please consider enabling this feature or consider overriding the tag (possibly with a comment about why).
      N:
      N:   If you use dpkg-buildflags, you may have to add hardening=+bindnow or hardening=+all to DEB_BUILD_MAINT_OPTIONS.
      N:
      N:   The relevant compiler flags are set in LDFLAGS.
      N:
      N:   Please refer to https://wiki.debian.org/Hardening for details.
      N:
      N:   Visibility: info
      N:   Show-Always: no
      N:   Check: binaries/hardening

* Re-enable dh_missing
dh_missing can be useful to detect files missed to be installed.
Ignore the static library via d/not-installed, see dh_missing(1).

### CODE REVIEW

**Comment by mvanderkolff** [comment]
Please
* Rebase to head;
* Add this as "misc. lintian fixes" to the changelog, thanking yourself (and remove the previous entry).

Thanks!

**Comment by cgzones** [comment]
I merged the four Debian Makefile patches and updated the Makefile, such that CPPFLAGS and LDFLAGS are propagated.

**Review by mvanderkolff — APPROVED** [review]
The changelog doesn't seem quite correct (because the upload is attributable to me). But the subsection is correct.

I'll correct the changelog. Thanks!

**Comment by cgzones** [comment]
I included the authorship line in the changelog to create a valid entry.

Thanks for maintaining jbigkit!

**Comment by malaterre** [comment]
Hi both !

Thanks for the update. If you have some time, could you dig this:

* https://buildd.debian.org/status/fetch.php?pkg=jbigkit&arch=ppc64el&ver=2.1-5&stamp=1665133130&raw=0

Some suggestions:
- if you have access to pp64el arch it should be easy to reproduce
- if not, you can try on amd64 + the fancy fsanitize gcc options


Thanks !

**Pull request merged**
